development:
  dialect: postgres
  database: kxoynnxy
  user: kxoynnxy
  password: mZGDKfXrETdN5_aNnF6l-sOBEvamKEd9
  host: rogue.db.elephantsql.com
  pool: 5
  port: 5432

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5433/myapp_test"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://postgres:postgres@127.0.0.1:5433/myapp_production"}}